### ISSUE TITLE
Configuration file partially ignored

### ISSUE THREAD

**Issue by viluon** [gamax92/cclite#20]
CCLite Frames 64 on Windows 7 64bit seems to _partially_ ignore the configuration file.
![https://gyazo.com/71608ba9397ebb5d2af0941ae3adedcb](https://i.gyazo.com/71608ba9397ebb5d2af0941ae3adedcb.png)
FPS is higher than the lock value and screen size does not change. Other settings, such as use https and GUI scale seem to work correctly, however. No errors are shown after closing the configuration file frame, only 'Loaded new config'.

*EDIT*: It looks like CCLite doesn't clean up the configuration file from a previous version. I have reset my configuration file to the default one of the current version. CCLite Frames still ignores the configuration (partly?) but the single computer build follows it to the point.

- [ ] Find out what is actually happening to the files
- [ ] Is this related only to Frames or also to the single PC build?
- [ ] Fix the bug

**Comment by gamax92** [comment]
This should be fixed now, CCLite was hard coding 51x19 for the Computers and will now use config values, note that changing the config will not update any existing computers, and that's intentional.
