### ISSUE TITLE
Font Rendering

### ISSUE THREAD

**Issue by viluon** [gamax92/cclite#21]
Appearance on CCEmuRedux: 
![](https://i.gyazo.com/942c2aa04103a0b7c84b71ddbbd08e86.png)
vs appearance on CCLite: 
![](https://i.gyazo.com/898f4cc1529b1a38f7cea842d4777e31.png)
the CCLite font ends just at the very border of the pixel, which has a negative impact on readability and doesn't look very nice. The default (CCEmuRedux follows vanilla AFAIK) spacing makes a text-centred look.

However, this has changed with CC 1.76. Since the font has now special characters, it wouldn't look correctly with the repositioned version. It is up to you if you'd like to reposition only non-special characters or leave it the way it is @gamax92.

**Comment by gamax92** [comment]
I'm going for what CC does, which I haven't checked in a while (and it keeps constantly changing ...)

Will take a look.

**Comment by gamax92** [comment]
All current character (1.75) are accurately placed.
